import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { ToggleProvider } from "./_contexts/toggle-context";

import { cn } from "./_libs/utils";

import "./globals.css";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pig Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn("bg-slate-950 text-white", spaceGrotesk.className)}>
        <ToggleProvider>{children}</ToggleProvider>
      </body>
    </html>
  );
}
